using RT.Util.Lingo;

namespace ExpertSokoban
{
#if DEBUG
    [LingoAutoGenerated]
#endif
    [LingoStringClass, LingoInGroup(TranslationGroup.About)]
    public partial class AboutBoxTranslation
    {
        [LingoNotes("Title bar.")]
        public TrString AboutBox = "About Expert Sokoban";

        [LingoNotes("This is displayed in a box in the About dialog. Please feel free to add a line to credit yourself for your translation work.")]
        public TrString lblCredits = "Credits:\r\n    Programming: Timwi, Roman\r\n    Graphics: Roman, Timwi\r\n    Testing: Hawthorn";

        public TrString btnOK = "OK";
    }
}
