using RT.Util.Lingo;

namespace ExpertSokoban
{
#if DEBUG
    [LingoAutoGenerated]
#endif
    [LingoStringClass, LingoInGroup(TranslationGroup.Highscores)]
    public partial class HighscoresFormTranslation
    {
        [LingoNotes("Title bar.")]
        public TrString HighscoresForm = "Highscores";

        public TrString btnOK = "OK";
    }
}
