using RT.Util.Lingo;

namespace ExpertSokoban
{
#if DEBUG
    [LingoAutoGenerated]
#endif
    [LingoStringClass, LingoInGroup(TranslationGroup.ContextMenu)]
    public partial class ContextMenuTranslation
    {
        public TrString mnuContextPlay = "Pl&ay this level";

        public TrString mnuContextEdit = "&Edit this level";

        public TrString mnuContextHighscores = "Show &highscores";

        public TrString mnuContextNewLevel = "C&reate a new level here";

        public TrString mnuContextNewComment = "&Insert a comment here";

        public TrString mnuContextCut = "C&ut";

        public TrString mnuContextCopy = "&Copy";

        public TrString mnuContextPaste = "&Paste";

        public TrString mnuContextDelete = "&Delete";

        public TrString mnuContextHide = "Hide &level list";
    }
}
